name: tflite_flutter_helper
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 0.3.1-dev
homepage: https://github.com/Yugu33/tflite_flutter_helper

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  quiver: ^3.2.1
  path_provider: ^2.1.2
  tflite_flutter: ^0.10.1
  tuple: ^2.0.2
  camera: ^0.10.5+5
  ffi: ^2.1.0
  image: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
